spec-version: 0.36.0  # Avoid legacy behaviour of Hpack

name: crypton-asn1-parse
version: 0.9.6
synopsis: A monadic parser combinator for a ASN.1 stream.
description: |
  A library providing a monadic parser combinator for use with a stream of
  Abstract Syntax Notation One (ASN.1) standard values.
copyright: Vincent Hanquez <vincent@snarc.org>
author: Vincent Hanquez <vincent@snarc.org>
maintainer:
- Mike Pilgrem <public@pilgrem.com>
- Kazu Yamamoto <kazu@iij.ad.jp>
category: Data
stability: experimental
github: mpilgrem/crypton-asn1/parse
homepage: https://github.com/mpilgrem/crypton-asn1
extra-doc-files:
- CHANGELOG.md
- README.md

language: Haskell98
other-extensions: LambdaCase

library:
  source-dirs: src
  dependencies:
  - base >= 4.13 && < 5
  - bytestring
  - crypton-asn1-types >= 0.3.6 && < 0.4
  exposed-modules:
  - Data.ASN1.Parse
  reexported-modules:
  - Data.ASN1.Types
  ghc-options:
  - -Wall
