spec-version: 0.36.0 # Avoid legacy behaviour of Hpack

name: crypton-asn1-types
version: 0.3.5
synopsis: ASN.1 types
description: |
  A library providing types representing the Abstract Syntax Notation One
  (ASN.1) standard.
copyright: Vincent Hanquez <vincent@snarc.org>
author: Vincent Hanquez <vincent@snarc.org>
maintainer:
- Mike Pilgrem <public@pilgrem.com>
- Kazu Yamamoto <kazu@iij.ad.jp>
category: Data
stability: experimental
github: mpilgrem/crypton-asn1
homepage: http://github.com/mpilgrem/crypton-asn1
extra-doc-files:
- CHANGELOG.md
- README.md

language: Haskell98
other-extensions: CPP

library:
  source-dirs: src
  dependencies:
  - base >= 3 && < 5
  - base16
  - bytestring
  - hourglass
  exposed-modules:
  - Data.ASN1.BitArray
  - Data.ASN1.OID
  - Data.ASN1.Pretty
  - Data.ASN1.Types
  - Data.ASN1.Types.String
  - Data.ASN1.Types.Lowlevel
  ghc-options:
  - -Wall
