spec-version: 0.36.0 # Avoid legacy behaviour of Hpack

name: crypton-asn1-encoding
version: 0.9.6
synopsis: ASN1 data reader and writer in RAW, BER and DER forms
description: |
  ASN1 data reader and writer in raw form with supports for high level forms of
  ASN1 (BER, and DER).
copyright: Vincent Hanquez <vincent@snarc.org>
author: Vincent Hanquez <vincent@snarc.org>
maintainer:
- Mike Pilgrem <public@pilgrem.com>
- Kazu Yamamoto <kazu@iij.ad.jp>
category: Data
stability: experimental
github: mpilgrem/crypton-asn1/encoding
homepage: https://github.com/mpilgrem/crypton-asn1
extra-doc-files:
- CHANGELOG.md
- README.md

library:
  source-dirs: src
  exposed-modules:
  - Data.ASN1.Error
  - Data.ASN1.BinaryEncoding
  - Data.ASN1.BinaryEncoding.Raw
  - Data.ASN1.Encoding
  - Data.ASN1.Stream
  - Data.ASN1.Object
  - Data.ASN1.Prim
  dependencies:
  - base >= 3 && < 5
  - bytestring
  - hourglass >= 0.2.6
  - crypton-asn1-types >= 0.3.0 && < 0.4
  ghc-options:
  - -Wall
  - -fwarn-tabs

tests:
  tests-asn1-encoding:
    source-dirs:
    - tests
    - src
    main: Tests.hs
    dependencies:
    - base >= 3 && < 7
    - bytestring
    - mtl
    - tasty
    - tasty-quickcheck
    - crypton-asn1-types
    - crypton-asn1-encoding
    - hourglass
    ghc-options:
    - -Wall
    - -fno-warn-orphans
    - -fno-warn-missing-signatures
