spec-version: 0.36.0 # Avoid legacy behaviour of Hpack

name: crypton-asn1-encoding
version: 0.9.7
synopsis: ASN.1 data (raw, BER or DER) readers and writers
description: |
  A library providing readers and writers of data following the Abstract Syntax
  Notation One (ASN.1) standard in raw form or in the high-level forms of Basic
  Encoding Rules (BER) and Distinguished Encoding Rules (DER).
copyright: Vincent Hanquez <vincent@snarc.org>
author: Vincent Hanquez <vincent@snarc.org>
maintainer:
- Mike Pilgrem <public@pilgrem.com>
- Kazu Yamamoto <kazu@iij.ad.jp>
category: Data
stability: experimental
github: mpilgrem/crypton-asn1/encoding
homepage: https://github.com/mpilgrem/crypton-asn1
extra-doc-files:
- CHANGELOG.md
- README.md

other-extensions:
- CPP
- RankNTypes
- ViewPatterns

ghc-options:
- -Wall

library:
  source-dirs: src
  exposed-modules:
  - Data.ASN1.Error
  - Data.ASN1.BinaryEncoding
  - Data.ASN1.BinaryEncoding.Raw
  - Data.ASN1.Encoding
  - Data.ASN1.Prim
  reexported-modules:
  - Data.ASN1.Stream
  - Data.ASN1.Types
  dependencies:
  - base >= 4.13 && < 5
  - bytestring
  - hourglass >= 0.2.6
  - crypton-asn1-types >= 0.3.6 && < 0.4

tests:
  tests-asn1-encoding:
    source-dirs:
    - tests
    - src
    main: Tests.hs
    dependencies:
    - base >= 4.13 && < 5
    - bytestring
    - mtl
    - tasty
    - tasty-quickcheck
    - crypton-asn1-types >= 0.3.6 && < 0.4
    - crypton-asn1-encoding
    - hourglass
